#!/usr/bin/env python3

print("Content-Type: text/html")
print()  # Empty line to end headers

print("<!DOCTYPE html>")
print("<html>")
print("<head><title>Python CGI Test</title></head>")
print("<body>")
print("<h1>Hello from Python CGI!</h1>")
print("<p>This page was generated by a Python script.</p>")
print("</body>")
print("</html>")
